version: '3.8'

services:
  frontend:
    build: .
    image: new-frontend
    container_name: remix-frontend
    ports:
      - "4200:4200"
    environment:
      - PORT=4200
      - NODE_ENV=production

